// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@yourcompany.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/banner/generate": {
            "post": {
                "description": "Accepts a banner generation request and returns a generation ID immediately.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "banner"
                ],
                "summary": "Start async banner image generation",
                "parameters": [
                    {
                        "description": "Generation parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BannerGenerationRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/models.BannerGenerationAccepted"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BannerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BannerErrorResponse"
                        }
                    }
                }
            }
        },
        "/banner/generate/{id}": {
            "get": {
                "description": "Returns status, variants (URLs / b64) and failure info for a generation job.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "banner"
                ],
                "summary": "Get banner generation status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Generation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BannerGenerationResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.BannerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.BannerErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the general health status of the query assistant service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "$ref": "#/definitions/models.HealthResponse"
                        }
                    }
                }
            }
        },
        "/live": {
            "get": {
                "description": "Returns the liveness status of the query assistant",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "Service is alive",
                        "schema": {
                            "$ref": "#/definitions/models.HealthResponse"
                        }
                    }
                }
            }
        },
        "/query/execute": {
            "post": {
                "description": "Convert a natural language prompt to SQL and execute it against ClickHouse with site_id filtering for multi-tenancy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "query"
                ],
                "summary": "Execute a natural language query with site filtering",
                "parameters": [
                    {
                        "description": "Query request with required site_id for multi-tenant filtering",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful query execution with results filtered by site_id",
                        "schema": {
                            "$ref": "#/definitions/models.QueryResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request - missing site_id or invalid format",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or missing token",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "408": {
                        "description": "Query timeout",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/query/generate": {
            "post": {
                "description": "Generate a SQL query from natural language prompt without executing it",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "query"
                ],
                "summary": "Generate SQL query",
                "parameters": [
                    {
                        "description": "Generation request with site_id",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QueryGenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Generated SQL query with metadata",
                        "schema": {
                            "$ref": "#/definitions/models.QueryGenerateResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/query/history": {
            "get": {
                "description": "Retrieve the history of previously executed queries with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "query"
                ],
                "summary": "Get query history",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by site ID",
                        "name": "site_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of historical queries",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.QueryHistory"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/query/validate": {
            "post": {
                "description": "Validate a SQL query for syntax and security without executing it, with optimization suggestions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "query"
                ],
                "summary": "Validate a SQL query",
                "parameters": [
                    {
                        "description": "Query to validate with site_id",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QueryValidateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Validation result with warnings and optimization suggestions",
                        "schema": {
                            "$ref": "#/definitions/models.QueryValidationResult"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns the readiness status of the query assistant including dependency checks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "Service is ready to accept requests",
                        "schema": {
                            "$ref": "#/definitions/models.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service is not ready - dependencies not available",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schema": {
            "get": {
                "description": "Get the complete database schema including all tables and columns",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schema"
                ],
                "summary": "Get database schema",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SchemaInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schema/refresh": {
            "post": {
                "description": "Manually refresh the database schema cache",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schema"
                ],
                "summary": "Refresh schema cache",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schema/table/{table}": {
            "get": {
                "description": "Get schema information for a specific table",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schema"
                ],
                "summary": "Get table schema",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Table name",
                        "name": "table",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TableSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BannerErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "VALIDATION_ERROR"
                },
                "error": {
                    "type": "string",
                    "example": "Banner generation request failed"
                },
                "message": {
                    "type": "string",
                    "example": "inputs.headline is required"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "models.BannerGenerationAccepted": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "generation_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "type": "string",
                    "example": "in_progress"
                }
            }
        },
        "models.BannerGenerationRequest": {
            "type": "object",
            "required": [
                "inputs",
                "language",
                "output"
            ],
            "properties": {
                "inputs": {
                    "$ref": "#/definitions/models.BannerInputs"
                },
                "language": {
                    "description": "e.g. \"en\"",
                    "type": "string"
                },
                "output": {
                    "$ref": "#/definitions/models.BannerOutputParams"
                }
            }
        },
        "models.BannerGenerationResult": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "failure_reason": {
                    "type": "string",
                    "example": "dall-e-3 generation failed: rate limit"
                },
                "generation_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:05Z"
                },
                "variants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BannerVariant"
                    }
                }
            }
        },
        "models.BannerInputs": {
            "type": "object",
            "properties": {
                "creative_description": {
                    "type": "string",
                    "example": "Gold coins and dramatic lighting"
                },
                "cta_text": {
                    "type": "string",
                    "example": "Claim Now"
                },
                "headline": {
                    "type": "string",
                    "example": "Get 100% Bonus on First Deposit"
                },
                "secondary_text": {
                    "type": "string",
                    "example": "Up to $500 matched. T\u0026Cs apply."
                },
                "visual_style": {
                    "type": "string",
                    "example": "dark_luxury"
                }
            }
        },
        "models.BannerOutputParams": {
            "type": "object",
            "properties": {
                "format": {
                    "type": "string",
                    "example": "url"
                },
                "height": {
                    "type": "integer",
                    "example": 1024
                },
                "max_size_kb": {
                    "type": "integer",
                    "example": 2048
                },
                "width": {
                    "type": "integer",
                    "example": 1792
                }
            }
        },
        "models.BannerVariant": {
            "type": "object",
            "properties": {
                "b64_json": {
                    "type": "string"
                },
                "index": {
                    "type": "integer",
                    "example": 0
                },
                "revised_prompt": {
                    "type": "string",
                    "example": "A high-quality promotional banner..."
                },
                "url": {
                    "type": "string",
                    "example": "https://oaidalleapiprodscus.blob.core.windows.net/..."
                }
            }
        },
        "models.ColumnMetadata": {
            "type": "object",
            "properties": {
                "database_type": {
                    "type": "string",
                    "example": "UInt64"
                },
                "name": {
                    "type": "string",
                    "example": "user_id"
                },
                "nullable": {
                    "type": "boolean",
                    "example": false
                },
                "position": {
                    "type": "integer",
                    "example": 0
                },
                "sample_value": {
                    "type": "string",
                    "example": "12345"
                },
                "type": {
                    "type": "string",
                    "example": "UInt64"
                }
            }
        },
        "models.ColumnSchema": {
            "type": "object",
            "properties": {
                "default_value": {
                    "description": "New fields",
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "example": "Unique user identifier"
                },
                "is_nullable": {
                    "type": "boolean",
                    "example": false
                },
                "is_partition_key": {
                    "type": "boolean",
                    "example": false
                },
                "is_primary_key": {
                    "type": "boolean",
                    "example": true
                },
                "is_sorting_key": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "user_id"
                },
                "type": {
                    "type": "string",
                    "example": "UInt64"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "VALIDATION_ERROR"
                },
                "details": {
                    "type": "object"
                },
                "error": {
                    "type": "string",
                    "example": "Query validation failed"
                },
                "message": {
                    "type": "string",
                    "example": "Query contains forbidden operation: DROP"
                },
                "query_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                }
            }
        },
        "models.HealthCheckDetail": {
            "type": "object",
            "properties": {
                "clickhouse": {
                    "type": "string",
                    "example": "ok"
                },
                "openai": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "models.HealthResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "$ref": "#/definitions/models.HealthCheckDetail"
                },
                "service": {
                    "type": "string",
                    "example": "query-assistant"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "models.PaginationInfo": {
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean",
                    "example": true
                },
                "has_previous": {
                    "type": "boolean",
                    "example": false
                },
                "next_page": {
                    "type": "integer",
                    "example": 2
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 100
                },
                "previous_page": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer",
                    "example": 10
                },
                "total_rows": {
                    "type": "integer",
                    "example": 1000
                }
            }
        },
        "models.QueryGenerateRequest": {
            "type": "object",
            "required": [
                "prompt",
                "site_id"
            ],
            "properties": {
                "prompt": {
                    "type": "string",
                    "example": "Show GGR for last month"
                },
                "site_id": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 123
                }
            }
        },
        "models.QueryGenerateResponse": {
            "type": "object",
            "properties": {
                "complexity": {
                    "type": "string",
                    "example": "medium"
                },
                "generated_sql": {
                    "type": "string",
                    "example": "SELECT SUM(bet_amount) - SUM(win_amount) as GGR FROM transactions WHERE site_id = 123 AND created_at \u003e= today() - 30 LIMIT 1"
                },
                "prompt": {
                    "type": "string",
                    "example": "Show GGR for last month"
                },
                "site_id": {
                    "type": "integer",
                    "example": 123
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                }
            }
        },
        "models.QueryHistory": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "error": {
                    "type": "string"
                },
                "execution_time": {
                    "type": "number",
                    "example": 0.156
                },
                "generated_sql": {
                    "type": "string",
                    "example": "SELECT month, SUM(sales) FROM sales_table WHERE site_id = 123 GROUP BY month"
                },
                "prompt": {
                    "type": "string",
                    "example": "Show total sales by month"
                },
                "query_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "row_count": {
                    "type": "integer",
                    "example": 12
                },
                "site_id": {
                    "type": "integer",
                    "example": 123
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "user_id": {
                    "type": "string",
                    "example": "user123"
                }
            }
        },
        "models.QueryRequest": {
            "type": "object",
            "required": [
                "site_id"
            ],
            "properties": {
                "context": {
                    "type": "object"
                },
                "include_schema": {
                    "description": "Response options",
                    "type": "boolean",
                    "example": true
                },
                "include_stats": {
                    "type": "boolean",
                    "example": true
                },
                "page": {
                    "description": "Pagination options",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "maximum": 10000,
                    "minimum": 1,
                    "example": 100
                },
                "prompt": {
                    "type": "string",
                    "example": "Show me the top 10 users by total purchase amount in the last 30 days"
                },
                "site_id": {
                    "description": "Required site_id parameter (numeric)",
                    "type": "integer",
                    "minimum": 1,
                    "example": 123
                },
                "timeout": {
                    "type": "integer",
                    "maximum": 300,
                    "minimum": 1,
                    "example": 30
                }
            }
        },
        "models.QueryResponse": {
            "type": "object",
            "properties": {
                "cache_key": {
                    "type": "string"
                },
                "columns": {
                    "description": "New fields for column metadata and pagination",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ColumnMetadata"
                    }
                },
                "execution_time": {
                    "type": "number",
                    "example": 0.234
                },
                "generated_sql": {
                    "type": "string",
                    "example": "SELECT user_id, SUM(amount) as total FROM purchases WHERE site_id = 123 AND created_at \u003e= today() - 30 GROUP BY user_id ORDER BY total DESC LIMIT 10"
                },
                "pagination": {
                    "$ref": "#/definitions/models.PaginationInfo"
                },
                "prompt": {
                    "type": "string",
                    "example": "Show me the top 10 users by total purchase amount"
                },
                "query_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "row_count": {
                    "description": "Legacy fields (kept for backward compatibility)",
                    "type": "integer",
                    "example": 10
                },
                "statistics": {
                    "$ref": "#/definitions/models.QueryStatistics"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "warnings": {
                    "description": "Additional metadata",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['Query processed large amount of data']"
                    ]
                }
            }
        },
        "models.QueryStatistics": {
            "type": "object",
            "properties": {
                "bytes_processed": {
                    "type": "integer",
                    "example": 1048576
                },
                "cache_hit": {
                    "type": "boolean",
                    "example": false
                },
                "execution_time_ms": {
                    "type": "number",
                    "example": 234.5
                },
                "partitions_accessed": {
                    "type": "integer",
                    "example": 3
                },
                "rows_returned": {
                    "type": "integer",
                    "example": 100
                },
                "total_rows": {
                    "type": "integer",
                    "example": 50000
                }
            }
        },
        "models.QueryValidateRequest": {
            "type": "object",
            "required": [
                "query",
                "site_id"
            ],
            "properties": {
                "query": {
                    "type": "string",
                    "example": "SELECT * FROM users WHERE site_id = 123 LIMIT 10"
                },
                "site_id": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 123
                }
            }
        },
        "models.QueryValidationResult": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "estimated_cost": {
                    "type": "string",
                    "example": "low"
                },
                "estimated_rows": {
                    "description": "New fields",
                    "type": "integer",
                    "example": 10000
                },
                "operations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "optimizations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tables": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "valid": {
                    "type": "boolean"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.SchemaInfo": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string",
                    "example": "analytics"
                },
                "tables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TableSchema"
                    }
                }
            }
        },
        "models.TableSchema": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ColumnSchema"
                    }
                },
                "description": {
                    "type": "string",
                    "example": "User information table"
                },
                "engine": {
                    "type": "string",
                    "example": "MergeTree"
                },
                "last_modified": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "users"
                },
                "partition_key": {
                    "description": "New fields",
                    "type": "string",
                    "example": "toYYYYMM(created_at)"
                },
                "row_count": {
                    "type": "integer",
                    "example": 1000000
                },
                "size_bytes": {
                    "type": "integer",
                    "example": 104857600
                },
                "sorting_key": {
                    "type": "string",
                    "example": "user_id"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Query generation and execution operations with multi-tenant support",
            "name": "query"
        },
        {
            "description": "Database schema information",
            "name": "schema"
        },
        {
            "description": "Health and readiness checks",
            "name": "health"
        },
        {
            "description": "Async AI banner image generation via DALL-E 3. POST to start, GET to poll status.",
            "name": "banner"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Query Assistant API",
	Description:      "An intelligent query assistant that uses ChatGPT to generate and execute ClickHouse queries based on natural language prompts with multi-tenant support.\n\n## Features\n- **Natural Language Processing**: Convert plain English prompts to ClickHouse SQL queries\n- **Multi-Tenant Support**: All queries are filtered by site_id for data isolation\n- **Schema-Aware**: Understands your database schema for accurate query generation\n- **Business Logic**: Built-in understanding of gaming metrics (GGR = Bet - Win)\n- **Query Execution**: Automatically executes generated queries with timeout protection\n- **Secure**: Query validation, site_id enforcement, and execution limits\n- **Observable**: Structured logging with Graylog integration\n- **Banner Generation**: Async AI-powered marketing banner image generation via DALL-E 3\n\n## Important Business Rules\n- **GGR Calculation**: Gross Gaming Revenue is always calculated as Total Bet - Total Win\n- **Site Isolation**: All queries are automatically filtered by site_id\n- **Archive Tables**: Queries on archive tables always include created_at filters\n- **RMT Tables**: Tables with 'rmt' in name use FINAL keyword for consistency\n\n## Multi-Tenant Architecture\nAll API endpoints require a numeric site_id parameter to ensure data isolation between different sites/tenants.\nThe system automatically adds WHERE site_id = {your_site_id} to all generated queries.\n\n## Authentication\nMost endpoints require a Bearer token in the Authorization header:\nAuthorization: Bearer {your-jwt-token}\n\n## Banner Image Generation\nBanner generation is asynchronous. POST to /api/v1/banner/generate to start a job,\nthen poll GET /api/v1/banner/generate/{id} until status is \"completed\" or \"failed\".\nDefault variant count is 4 images per request (configurable via banner.variant_count in config).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
